import os
from pathlib import Path

BASE_DIR = Path(__file__).parent.resolve()

# Directory structure
APP_DIR = BASE_DIR / "app"
MODELS_DIR = BASE_DIR / "models"
DATA_DIR = BASE_DIR / "data"
STATIC_DIR = BASE_DIR / "static"
TEMPLATES_DIR = BASE_DIR / "templates"

# Networking
HOST = "0.0.0.0"
PORT = 5555

# File Paths
HISTORY_FILE = DATA_DIR / "history.json"
YOLO_MODEL_PATH = str(MODELS_DIR / "yolov8n.pt")
STATIC_VIDEO_PATH = str(STATIC_DIR / "assets" / "chicken_demo.mp4")

# Hardware & Video
WEBCAM_INDICES = [0, 2]  # put 2 if linux, put 1 if macos. 0 is constant
FRAME_WIDTH = 640
FRAME_HEIGHT = 480
JPEG_QUALITY = 70
FRAME_DELAY = 1 / 10
THERMAL_FRAME_DELAY = 1 / 10

# AI Thresholds
YOLO_CONFIDENCE_THRESHOLD = 0.25
YOLO_IOU_THRESHOLD_NMS = 0.45
YOLO_TARGET_CLASSES = [14]
CLASSIFICATION_CONFIDENCE_THRESHOLD = 0.65
CLASSIFICATION_INTERVAL_FRAMES = 20
MIN_FRAMES_FOR_CLASSIFICATION = 15
MAX_CLASSIFICATION_COUNT = 5

# Behavior Analysis
MOVEMENT_HISTORY_LENGTH = 60
LETHARGY_TIMEFRAME_SECONDS = 30
LETHARGY_FLOCK_ACTIVE_THRESHOLD = 2.0
LETHARGY_INDIVIDUAL_THRESHOLD_RATIO = 0.2
DISEASE_HISTORY_LENGTH = 10
DISEASE_ALERT_THRESHOLD_COUNT = 3

# Tracker
TRACKER_MAX_DISTANCE = 100
MAX_UNSEEN_FRAMES_TRACKER = 25

# History
MAX_HISTORY_ENTRIES = 500
